import { AppTheme } from '../types/timetable';

export const APP_THEMES: AppTheme[] = [
  // 🌸 1. HOA ANH ĐÀO (Blossom Pink)
  {
    id: 'girl-blossom',
    name: 'Hoa Anh Đào',
    subtitle: 'Hồng pastel ngọt ngào, dịu dàng',
    gender: 'girl',
    badge: 'Anh Đào',
    previewColors: ['#db2777', '#f472b6', '#fce7f3'],
    bodyBg: 'bg-pink-50/70',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-pink-600 via-rose-500 to-pink-500',
    primaryColor: 'bg-pink-500 text-white',
    primaryHover: 'hover:bg-pink-600',
    accentBadge: 'bg-pink-100 text-pink-700 border-pink-300',
    tableHeaderBg: 'bg-pink-100/80 text-pink-900 border-pink-200',
    tableBorder: 'border-pink-200',
    cellHoverBg: 'hover:bg-pink-50',
    alteredSlotRing: 'ring-2 ring-pink-500 border-pink-400 bg-pink-50/70',
    accentText: 'text-pink-600',
    containerBorder: 'border-pink-200/90 shadow-pink-100/40',
    btnPrimary: 'bg-gradient-to-r from-pink-500 to-rose-500 hover:from-pink-600 hover:to-rose-600 text-white shadow-pink-200',
    mascotEmoji: '🌸',
    mascotName: 'Blossom Cat',
    mascotQuote: 'Một ngày học tập thật ngọt ngào và tràn đầy năng lượng! ✨',
    cardHeaderBg: 'bg-pink-50/90 text-pink-950 border-pink-200',
    todayMorningBg: 'bg-rose-50/60 border-rose-200',
    todayAfternoonBg: 'bg-pink-50/60 border-pink-200',
  },

  // 🌊 2. BIỂN XANH (Ocean Blue)
  {
    id: 'theme-ocean',
    name: 'Biển Xanh',
    subtitle: 'Bầu trời và sóng biển pastel trong lành',
    gender: 'neutral',
    badge: 'Biển Cả',
    previewColors: ['#0284c7', '#38bdf8', '#e0f2fe'],
    bodyBg: 'bg-sky-50/70',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-sky-600 via-blue-600 to-cyan-600',
    primaryColor: 'bg-sky-600 text-white',
    primaryHover: 'hover:bg-sky-700',
    accentBadge: 'bg-sky-100 text-sky-800 border-sky-300',
    tableHeaderBg: 'bg-sky-100/80 text-sky-950 border-sky-200',
    tableBorder: 'border-sky-200',
    cellHoverBg: 'hover:bg-sky-50',
    alteredSlotRing: 'ring-2 ring-sky-500 border-sky-400 bg-sky-50/70',
    accentText: 'text-sky-600',
    containerBorder: 'border-sky-200/90 shadow-sky-100/40',
    btnPrimary: 'bg-gradient-to-r from-sky-600 to-blue-600 hover:from-sky-700 hover:to-blue-700 text-white shadow-sky-200',
    mascotEmoji: '🌊',
    mascotName: 'Dolphin Blue',
    mascotQuote: 'Tâm trí hanh thông, học đâu hiểu đó như sóng khơi! 🐬',
    cardHeaderBg: 'bg-sky-50/90 text-sky-950 border-sky-200',
    todayMorningBg: 'bg-sky-50/60 border-sky-200',
    todayAfternoonBg: 'bg-blue-50/60 border-blue-200',
  },

  // 🌌 3. KHÔNG GIAN (Cosmic Space)
  {
    id: 'theme-space',
    name: 'Không Gian',
    subtitle: 'Ánh trăng, vì sao và hành tinh huyền ảo',
    gender: 'neutral',
    badge: 'Vũ Trụ',
    previewColors: ['#4338ca', '#818cf8', '#e0e7ff'],
    bodyBg: 'bg-indigo-50/80',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-indigo-900 via-purple-900 to-slate-900',
    primaryColor: 'bg-indigo-600 text-white',
    primaryHover: 'hover:bg-indigo-700',
    accentBadge: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    tableHeaderBg: 'bg-indigo-100/80 text-indigo-950 border-indigo-200',
    tableBorder: 'border-indigo-200',
    cellHoverBg: 'hover:bg-indigo-50',
    alteredSlotRing: 'ring-2 ring-purple-500 border-purple-400 bg-indigo-50/70',
    accentText: 'text-indigo-600',
    containerBorder: 'border-indigo-200/90 shadow-indigo-100/40',
    btnPrimary: 'bg-gradient-to-r from-indigo-700 to-purple-700 hover:from-indigo-800 hover:to-purple-800 text-white shadow-indigo-300',
    mascotEmoji: '🌌',
    mascotName: 'Cosmic Star',
    mascotQuote: 'Chinh phục từng đỉnh cao tri thức cùng các vì sao! 🚀',
    cardHeaderBg: 'bg-indigo-50/90 text-indigo-950 border-indigo-200',
    todayMorningBg: 'bg-indigo-50/60 border-indigo-200',
    todayAfternoonBg: 'bg-purple-50/60 border-purple-200',
  },

  // 🌿 4. THIÊN NHIÊN (Nature Green)
  {
    id: 'theme-nature',
    name: 'Thiên Nhiên',
    subtitle: 'Xanh lá pastel, tươi mát và bình yên',
    gender: 'neutral',
    badge: 'Mầm Xanh',
    previewColors: ['#15803d', '#4ade80', '#dcfce7'],
    bodyBg: 'bg-emerald-50/70',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-emerald-700 via-green-600 to-teal-700',
    primaryColor: 'bg-emerald-600 text-white',
    primaryHover: 'hover:bg-emerald-700',
    accentBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    tableHeaderBg: 'bg-emerald-100/80 text-emerald-950 border-emerald-200',
    tableBorder: 'border-emerald-200',
    cellHoverBg: 'hover:bg-emerald-50',
    alteredSlotRing: 'ring-2 ring-emerald-500 border-emerald-400 bg-emerald-50/70',
    accentText: 'text-emerald-700',
    containerBorder: 'border-emerald-200/90 shadow-emerald-100/40',
    btnPrimary: 'bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white shadow-emerald-200',
    mascotEmoji: '🌿',
    mascotName: 'Forest Sprout',
    mascotQuote: 'Từng bước tích lũy vững vàng như mầm non vươn lên! 🌱',
    cardHeaderBg: 'bg-emerald-50/90 text-emerald-950 border-emerald-200',
    todayMorningBg: 'bg-emerald-50/60 border-emerald-200',
    todayAfternoonBg: 'bg-teal-50/60 border-teal-200',
  },

  // 🏮 5. TRUNG THU (Mid-Autumn)
  {
    id: 'theme-midautumn',
    name: 'Trung Thu',
    subtitle: 'Vàng kem ấm áp, ánh trăng và đèn lồng',
    gender: 'neutral',
    badge: 'Trăng Rằm',
    previewColors: ['#d97706', '#fbbf24', '#fef3c7'],
    bodyBg: 'bg-amber-50/75',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-amber-600 via-orange-600 to-rose-600',
    primaryColor: 'bg-amber-600 text-white',
    primaryHover: 'hover:bg-amber-700',
    accentBadge: 'bg-amber-100 text-amber-900 border-amber-300',
    tableHeaderBg: 'bg-amber-100/80 text-amber-950 border-amber-200',
    tableBorder: 'border-amber-200',
    cellHoverBg: 'hover:bg-amber-50',
    alteredSlotRing: 'ring-2 ring-amber-500 border-amber-400 bg-amber-50/70',
    accentText: 'text-amber-700',
    containerBorder: 'border-amber-200/90 shadow-amber-100/40',
    btnPrimary: 'bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-700 hover:to-orange-700 text-white shadow-amber-200',
    mascotEmoji: '🏮',
    mascotName: 'Golden Rabbit',
    mascotQuote: 'Sáng tỏ như trăng rằm, học tập rạng rỡ và ấm áp! 🥮',
    cardHeaderBg: 'bg-amber-50/90 text-amber-950 border-amber-200',
    todayMorningBg: 'bg-amber-50/60 border-amber-200',
    todayAfternoonBg: 'bg-orange-50/60 border-orange-200',
  },

  // 🎄 6. GIÁNG SINH (Christmas)
  {
    id: 'theme-christmas',
    name: 'Giáng Sinh',
    subtitle: 'Trắng xanh tuyết, cây thông và ngôi sao ấm',
    gender: 'neutral',
    badge: 'Mùa Đông',
    previewColors: ['#b91c1c', '#15803d', '#f1f5f9'],
    bodyBg: 'bg-slate-50/80',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-red-700 via-emerald-700 to-slate-900',
    primaryColor: 'bg-red-600 text-white',
    primaryHover: 'hover:bg-red-700',
    accentBadge: 'bg-red-100 text-red-800 border-red-200',
    tableHeaderBg: 'bg-red-50 text-red-950 border-red-200',
    tableBorder: 'border-red-200',
    cellHoverBg: 'hover:bg-emerald-50/50',
    alteredSlotRing: 'ring-2 ring-emerald-500 border-emerald-400 bg-emerald-50/60',
    accentText: 'text-red-600',
    containerBorder: 'border-red-200/80 shadow-red-100/40',
    btnPrimary: 'bg-gradient-to-r from-red-600 to-emerald-700 hover:from-red-700 hover:to-emerald-800 text-white shadow-red-200',
    mascotEmoji: '🎄',
    mascotName: 'Holiday Noel',
    mascotQuote: 'Giữ nụ cười ấm áp và rực rỡ như chuông ngân! ❄️',
    cardHeaderBg: 'bg-red-50/90 text-red-950 border-red-200',
    todayMorningBg: 'bg-red-50/60 border-red-200',
    todayAfternoonBg: 'bg-emerald-50/60 border-emerald-200',
  },

  // 💜 7. DREAMY LAVENDER
  {
    id: 'girl-lavender',
    name: 'Dreamy Lavender',
    subtitle: 'Oải hương tím thanh lịch mộng mơ',
    gender: 'girl',
    badge: 'Oải Hương',
    previewColors: ['#6b21a8', '#9333ea', '#e9d5ff'],
    bodyBg: 'bg-purple-50/70',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-purple-700 via-fuchsia-600 to-indigo-700',
    primaryColor: 'bg-purple-600 text-white',
    primaryHover: 'hover:bg-purple-700',
    accentBadge: 'bg-purple-100 text-purple-700 border-purple-300',
    tableHeaderBg: 'bg-purple-100/80 text-purple-950 border-purple-200',
    tableBorder: 'border-purple-200',
    cellHoverBg: 'hover:bg-purple-50',
    alteredSlotRing: 'ring-2 ring-purple-500 border-purple-400 bg-purple-50/70',
    accentText: 'text-purple-600',
    containerBorder: 'border-purple-200/90 shadow-purple-100/40',
    btnPrimary: 'bg-gradient-to-r from-purple-600 to-fuchsia-600 hover:from-purple-700 hover:to-fuchsia-700 text-white shadow-purple-200',
    mascotEmoji: '💜',
    mascotName: 'Lavender Bunny',
    mascotQuote: 'Nỗ lực nhỏ mỗi ngày sẽ tạo nên thành tích tuyệt vời! 💜',
    cardHeaderBg: 'bg-purple-50/90 text-purple-950 border-purple-200',
    todayMorningBg: 'bg-purple-50/60 border-purple-200',
    todayAfternoonBg: 'bg-fuchsia-50/60 border-fuchsia-200',
  },

  // 🍑 8. PEACH SUNSET
  {
    id: 'girl-peach',
    name: 'Peach Sunset',
    subtitle: 'Trái đào hoàng hôn rạng rỡ và ấm áp',
    gender: 'girl',
    badge: 'Trái Đào',
    previewColors: ['#c2410c', '#f97316', '#ffedd5'],
    bodyBg: 'bg-orange-50/60',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-orange-500 via-amber-500 to-rose-500',
    primaryColor: 'bg-orange-500 text-white',
    primaryHover: 'hover:bg-orange-600',
    accentBadge: 'bg-orange-100 text-orange-800 border-orange-300',
    tableHeaderBg: 'bg-orange-100/80 text-orange-950 border-orange-200',
    tableBorder: 'border-orange-200',
    cellHoverBg: 'hover:bg-orange-50',
    alteredSlotRing: 'ring-2 ring-orange-400 border-orange-300 bg-orange-50/70',
    accentText: 'text-orange-600',
    containerBorder: 'border-orange-200/90 shadow-orange-100/40',
    btnPrimary: 'bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600 text-white shadow-orange-200',
    mascotEmoji: '🍑',
    mascotName: 'Peach Bear',
    mascotQuote: 'Uống đủ nước, hít sâu và tập trung thật tốt nhé! 🧋',
    cardHeaderBg: 'bg-orange-50/90 text-orange-950 border-orange-200',
    todayMorningBg: 'bg-amber-50/60 border-amber-200',
    todayAfternoonBg: 'bg-orange-50/60 border-orange-200',
  },

  // ⚽ 9. SPORT NAVY
  {
    id: 'boy-navy',
    name: 'Sport Navy',
    subtitle: 'Năng động thể thao, mạnh mẽ và sắc nét',
    gender: 'boy',
    badge: 'Thể Thao',
    previewColors: ['#1e3a8a', '#2563eb', '#93c5fd'],
    bodyBg: 'bg-blue-50/50',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-blue-700 via-indigo-700 to-slate-900',
    primaryColor: 'bg-blue-600 text-white',
    primaryHover: 'hover:bg-blue-700',
    accentBadge: 'bg-blue-100 text-blue-800 border-blue-200',
    tableHeaderBg: 'bg-blue-100/70 text-blue-950 border-blue-200',
    tableBorder: 'border-blue-200',
    cellHoverBg: 'hover:bg-blue-50',
    alteredSlotRing: 'ring-2 ring-amber-400 border-amber-300 bg-amber-50/50',
    accentText: 'text-blue-600',
    containerBorder: 'border-blue-200/80 shadow-blue-100/40',
    btnPrimary: 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white shadow-blue-200',
    mascotEmoji: '⚡',
    mascotName: 'Thunder Warrior',
    mascotQuote: 'Giữ vững tốc độ và ghi điểm tuyệt đối trong học tập! ⚽',
    cardHeaderBg: 'bg-blue-50/90 text-blue-950 border-blue-200',
    todayMorningBg: 'bg-blue-50/60 border-blue-200',
    todayAfternoonBg: 'bg-indigo-50/60 border-indigo-200',
  },

  // 🚀 10. CYBER MINT
  {
    id: 'boy-cyber',
    name: 'Cyber Mint',
    subtitle: 'Công nghệ hiện đại, xanh bạc hà sắc bén',
    gender: 'boy',
    badge: 'Công Nghệ',
    previewColors: ['#064e3b', '#059669', '#a7f3d0'],
    bodyBg: 'bg-emerald-50/50',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-slate-900 via-emerald-800 to-teal-900',
    primaryColor: 'bg-emerald-600 text-white',
    primaryHover: 'hover:bg-emerald-700',
    accentBadge: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    tableHeaderBg: 'bg-emerald-100/70 text-emerald-950 border-emerald-200',
    tableBorder: 'border-emerald-200',
    cellHoverBg: 'hover:bg-emerald-50',
    alteredSlotRing: 'ring-2 ring-emerald-500 border-emerald-400 bg-emerald-50/40',
    accentText: 'text-emerald-600',
    containerBorder: 'border-emerald-200/80 shadow-emerald-100/40',
    btnPrimary: 'bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white shadow-emerald-200',
    mascotEmoji: '🚀',
    mascotName: 'Young Astronaut',
    mascotQuote: 'Tập trung cao độ và mở khóa mọi bài học phức tạp! 🌟',
    cardHeaderBg: 'bg-emerald-50/90 text-emerald-950 border-emerald-200',
    todayMorningBg: 'bg-emerald-50/60 border-emerald-200',
    todayAfternoonBg: 'bg-teal-50/60 border-teal-200',
  },

  // 🔥 11. CARBON NEON
  {
    id: 'boy-carbon',
    name: 'Carbon Neon',
    subtitle: 'Graphite nam tính kết hợp cam neon nổi bật',
    gender: 'boy',
    badge: 'Carbon',
    previewColors: ['#18181b', '#ea580c', '#fed7aa'],
    bodyBg: 'bg-stone-100/90',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-zinc-900 via-neutral-900 to-stone-900',
    primaryColor: 'bg-orange-600 text-white',
    primaryHover: 'hover:bg-orange-700',
    accentBadge: 'bg-orange-100 text-orange-800 border-orange-200',
    tableHeaderBg: 'bg-stone-200/80 text-stone-900 border-stone-300',
    tableBorder: 'border-stone-300',
    cellHoverBg: 'hover:bg-orange-50',
    alteredSlotRing: 'ring-2 ring-orange-500 border-orange-400 bg-orange-50/50',
    accentText: 'text-orange-600',
    containerBorder: 'border-stone-300 shadow-stone-200/50',
    btnPrimary: 'bg-gradient-to-r from-zinc-800 to-orange-600 hover:from-zinc-900 hover:to-orange-700 text-white shadow-orange-200',
    mascotEmoji: '🔥',
    mascotName: 'Fire Dragon',
    mascotQuote: 'Nhanh chóng, chuẩn xác và không thể cản bước! 🛹',
    cardHeaderBg: 'bg-stone-100 text-stone-950 border-stone-300',
    todayMorningBg: 'bg-stone-100 border-stone-300',
    todayAfternoonBg: 'bg-orange-50/60 border-orange-200',
  },

  // 🎓 12. CLASSIC INDIGO
  {
    id: 'neutral-indigo',
    name: 'Classic Indigo',
    subtitle: 'Thanh lịch, trang nhã chuẩn phong cách học đường',
    gender: 'neutral',
    badge: 'Cổ Điển',
    previewColors: ['#312e81', '#4f46e5', '#c7d2fe'],
    bodyBg: 'bg-slate-50',
    surfaceBg: 'bg-white/94',
    cardBg: 'bg-white/94 backdrop-blur-md',
    headerGradient: 'from-slate-800 via-indigo-900 to-slate-900',
    primaryColor: 'bg-indigo-600 text-white',
    primaryHover: 'hover:bg-indigo-700',
    accentBadge: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    tableHeaderBg: 'bg-slate-100 text-slate-800 border-slate-200',
    tableBorder: 'border-slate-200',
    cellHoverBg: 'hover:bg-indigo-50/50',
    alteredSlotRing: 'ring-2 ring-amber-400 border-amber-300 bg-amber-50/40',
    accentText: 'text-indigo-600',
    containerBorder: 'border-slate-200/90 shadow-slate-100/40',
    btnPrimary: 'bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-700 hover:to-blue-700 text-white shadow-indigo-200',
    mascotEmoji: '🎓',
    mascotName: 'Wise Owl',
    mascotQuote: 'Học tập mỗi ngày mở ra tương lai rạng ngời! 📚',
    cardHeaderBg: 'bg-slate-100 text-slate-900 border-slate-200',
    todayMorningBg: 'bg-slate-50 border-slate-200',
    todayAfternoonBg: 'bg-indigo-50/50 border-indigo-200',
  },
];

export const getThemeById = (themeId: string): AppTheme => {
  const found = APP_THEMES.find(t => t.id === themeId);
  return found || APP_THEMES[0];
};
